/* This file was generated by the Hex-Rays decompiler version 9.1.0.250226.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

void __stdcall sub_402029(HWND hDlg, int a2, int a3, int a4);
BOOL __stdcall DialogFunc(HWND hDlg, UINT a2, WPARAM a3, LPARAM a4);
char __stdcall sub_4023B9(int a1);
unsigned __int8 __stdcall sub_4023DA(int a1);
void __spoils<edx,ecx> sub_402439();
void __spoils<> sub_402498();
__int16 TlsCallback_0();
void sub_402567();

//-------------------------------------------------------------------------
// Data declarations

int dword_401000 = 0; // weak
CHAR byte_401004 = '\0'; // idb
char byte_401040 = '\x01'; // weak
CHAR String[19] =
{
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\x10'
}; // weak
int dword_401055 = 0; // weak
CHAR Buffer[] = { '\0', '\0' }; // idb
__int16 word_40106A = 0; // weak
__int16 word_40106E = 0; // weak
DWORD nSize = 80u; // idb
CHAR Caption[] = "Info"; // idb
CHAR Text = '\xFC'; // idb
CHAR aUsernameMustHa[] = "Username must have 4 letters minimum"; // idb
CHAR aUsernameCannot[] = "Username cannot exceed 15 letters"; // idb
CHAR byte_401119 = '\xEB'; // idb
CHAR byte_401140 = '\xF0'; // idb
CHAR byte_401169 = '\xEA'; // idb
CHAR byte_40119D = '\xE9'; // idb
CHAR byte_4011C4 = '\xF0'; // idb
int dword_4011E3 = 812520959; // weak
__thread char byte_4011E7 = '\x01'; // weak
int dword_40121C = 0; // weak
char byte_401221[12] = { '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0' }; // weak
__int16 word_40122D = 8192; // weak
// extern HMODULE (__stdcall *GetModuleHandleA)(LPCSTR lpModuleName);
// extern void (__stdcall __noreturn *ExitProcess)(UINT uExitCode);
// extern BOOL (__stdcall *GetComputerNameA)(LPSTR lpBuffer, LPDWORD nSize);
// extern BOOL (__stdcall *IsDebuggerPresent)();
// extern INT_PTR (__stdcall *DialogBoxParamA)(HINSTANCE hInstance, LPCSTR lpTemplateName, HWND hWndParent, DLGPROC lpDialogFunc, LPARAM dwInitParam);
// extern BOOL (__stdcall *EndDialog)(HWND hDlg, INT_PTR nResult);
// extern UINT (__stdcall *GetDlgItemTextA)(HWND hDlg, int nIDDlgItem, LPSTR lpString, int cchMax);
// extern BOOL (__stdcall *SetDlgItemTextA)(HWND hDlg, int nIDDlgItem, LPCSTR lpString);
// extern int (__stdcall *MessageBoxA)(HWND hWnd, LPCSTR lpText, LPCSTR lpCaption, UINT uType);
// extern int (*wsprintfA)(LPSTR, LPCSTR, ...);


//----- (00402029) --------------------------------------------------------
void __stdcall sub_402029(HWND hDlg, int a2, int a3, int a4)
{
  UINT DlgItemTextA; // eax
  int v5; // ecx
  int v6; // eax
  int v7; // edx
  int *v8; // edi
  int v9; // esi
  char v10; // bl
  unsigned int v11; // ecx
  int v12; // [esp+0h] [ebp-Ch] BYREF

  if ( a2 == 272 )
  {
    if ( byte_4011E7 == 1 )
      return;
    GetComputerNameA(Buffer, &nSize);
    if ( *(_WORD *)Buffer == 18766 && word_40106E == 17746 && word_40106A == 21576 )
    {
      sub_4023B9((int)&Text);
      MessageBoxA(0, &Text, Caption, 0x1040u);
      sub_4023B9((int)&Text);
      sub_402439();
      return;
    }
    sub_4023B9((int)&byte_401169);
    MessageBoxA(0, &byte_401169, Buffer, 0x1040u);
    sub_4023B9((int)&byte_401169);
    goto LABEL_21;
  }
  if ( a2 != 273 )
  {
    if ( a2 == 16 )
      EndDialog(hDlg, 0);
    return;
  }
  if ( a3 != 201 )
  {
    if ( a3 != 202 )
    {
      if ( a3 == 203 )
      {
        dword_401000 = (int)GetModuleHandleA(0);
        DialogBoxParamA((HINSTANCE)dword_401000, (LPCSTR)7, 0, DialogFunc, 0);
      }
      return;
    }
LABEL_21:
    EndDialog(hDlg, 0);
    return;
  }
  DlgItemTextA = GetDlgItemTextA(hDlg, 301, String, 21);
  if ( DlgItemTextA < 4 || DlgItemTextA > 0xF )
  {
    if ( DlgItemTextA )
    {
      if ( DlgItemTextA < 6 )
        SetDlgItemTextA(hDlg, 302, aUsernameMustHa);
      else
        SetDlgItemTextA(hDlg, 302, aUsernameCannot);
    }
    else
    {
      sub_4023B9((int)&byte_401119);
      SetDlgItemTextA(hDlg, 302, &byte_401119);
      sub_4023B9((int)&byte_401119);
    }
  }
  else
  {
    byte_401040 = DlgItemTextA;
    if ( String[0] == 32 )
    {
      sub_4023B9((int)&byte_401140);
      SetDlgItemTextA(hDlg, 302, &byte_401140);
      sub_4023B9((int)&byte_401140);
    }
    else
    {
      sub_402439();
      if ( GetDlgItemTextA(hDlg, 302, &byte_401004, 21) <= 0x10 )
      {
        v5 = 0;
        v6 = 0;
        v7 = 0;
        v8 = &dword_401055;
        v9 = 1;
        v10 = byte_401040;
        do
        {
          LOBYTE(v6) = String[v5];
          v6 = v9 ^ ((v9 + v9 * v6) << 17) & 0x7FFFF;
          LOBYTE(v6) = v6 + 53;
          *(_BYTE *)v8 = v6;
          v7 += v6;
          v8 = (int *)((char *)v8 + 1);
          ++v5;
          ++v9;
        }
        while ( (_BYTE)v5 != v10 );
        wsprintfA((LPSTR)&dword_40121C + 1, "%i", ~(dword_401055 * v7));
        sub_4023B9(4198941);
        sub_4023DA(4198941);
        v11 = 0;
        while ( *(&byte_401004 + v11) == (*(_BYTE *)(v11 + 4198941) ^ 0xBE) )
        {
          ++v11;
          if ( !*(&byte_401004 + v11) && !*(_BYTE *)(v11 + 4198941) && v11 > 5 )
          {
            wsprintfA((LPSTR)&dword_40121C + 1, "%i", &v12);
            sub_4023B9((int)&byte_40119D);
            sub_402439();
            MessageBoxA(0, &byte_40119D, Buffer, 0x1040u);
            sub_4023B9((int)&byte_40119D);
            return;
          }
        }
      }
      sub_4023B9((int)&byte_4011C4);
      SetDlgItemTextA(hDlg, 302, &byte_4011C4);
      sub_4023B9((int)&byte_4011C4);
    }
  }
}
// 401000: using guessed type int dword_401000;
// 401040: using guessed type char byte_401040;
// 401055: using guessed type int dword_401055;
// 40106A: using guessed type __int16 word_40106A;
// 40106E: using guessed type __int16 word_40106E;
// 4011E7: using guessed type char byte_4011E7;
// 40121C: using guessed type int dword_40121C;

//----- (00402378) --------------------------------------------------------
BOOL __stdcall DialogFunc(HWND hDlg, UINT a2, WPARAM a3, LPARAM a4)
{
  BOOL result; // eax

  if ( a2 != 272 )
  {
    if ( a2 == 273 )
    {
      if ( a3 != 300 )
        return result;
    }
    else if ( a2 != 16 )
    {
      return 0;
    }
    return EndDialog(hDlg, 0);
  }
  return result;
}

//----- (004023B9) --------------------------------------------------------
char __stdcall sub_4023B9(int a1)
{
  int i; // ecx
  char result; // al

  for ( i = 0; ; ++i )
  {
    result = *(_BYTE *)(a1 + i);
    if ( !result )
      break;
    *(_BYTE *)(a1 + i) = result ^ 0xBE;
  }
  return result;
}

//----- (004023DA) --------------------------------------------------------
unsigned __int8 __stdcall sub_4023DA(int a1)
{
  int v1; // ecx
  unsigned __int8 result; // al
  int v3; // ecx

  v1 = 0;
  while ( 1 )
  {
    result = *(_BYTE *)(a1 + v1);
    if ( !result )
      break;
    if ( result < 0x90u )
    {
      ++v1;
    }
    else
    {
      if ( result == 0x93 )
        *(_BYTE *)(v1 + 4198941) = -115;
      else
        --*(_BYTE *)(v1 + 4198941);
      ++v1;
    }
  }
  *(_WORD *)(v1 + 4198941) = -3437;
  v3 = v1 + 2;
  *(_WORD *)(v3 + 4198941) = -1029;
  *(_WORD *)(v3 + 4198943) = 234;
  return result;
}

//----- (00402439) --------------------------------------------------------
void __spoils<edx,ecx> sub_402439()
{
  bool v0; // zf
  int v1; // eax

  v0 = !IsDebuggerPresent();
  v1 = dword_401000;
  if ( v0
    && *(_DWORD *)(dword_401000 + 8290) == 10454031
    && *(_DWORD *)(dword_401000 + 8283) == 300367232
    && *(_DWORD *)(dword_401000 + 8935) == 1618333752 )
  {
    sub_402498();
  }
  else
  {
    *(_DWORD *)(dword_401000 + 8209) = dword_4011E3;
    *(_WORD *)(v1 + 8246) = 6635;
    sub_402498();
  }
}
// 401000: using guessed type int dword_401000;
// 4011E3: using guessed type int dword_4011E3;

//----- (00402498) --------------------------------------------------------
void __spoils<> sub_402498()
{
  _BYTE *v0; // eax
  _BYTE *v1; // eax
  int v2; // eax

  v0 = (_BYTE *)(dword_401000 + 8465);
  while ( *v0 != 0xCC || (_WORD)v0 == 8759 || (_WORD)v0 == 9381 || (_WORD)v0 == 9403 )
  {
    if ( (unsigned __int16)++v0 > 0x24DBu )
    {
      v1 = (_BYTE *)(dword_401000 + 12288);
      while ( *v1 != 0xCC )
      {
        if ( (unsigned __int16)++v1 > 0x315Bu )
          return;
      }
      break;
    }
  }
  v2 = dword_401000;
  *(_DWORD *)(dword_401000 + 8222) = dword_4011E3;
  *(_WORD *)(v2 + 8249) = 6635;
  *(_DWORD *)(v2 + 12524) = 2088880770;
  *(_DWORD *)(v2 + 12536) = 2088880770;
}
// 401000: using guessed type int dword_401000;
// 4011E3: using guessed type int dword_4011E3;

//----- (00402510) --------------------------------------------------------
__int16 TlsCallback_0()
{
  HMODULE ModuleHandleA; // eax
  int (*v1)(void); // ebx
  _DWORD *i; // eax

  ModuleHandleA = GetModuleHandleA(0);
  dword_401000 = (int)ModuleHandleA;
  if ( (_BYTE)dword_40121C == 1 )
  {
    for ( i = (_DWORD *)(dword_401000 + 4096); ; LOWORD(i) = (_WORD)i + 4 )
    {
      *i = 1145128260;
      if ( (unsigned __int16)i >= 0x1228u )
        break;
    }
  }
  else
  {
    LOBYTE(dword_40121C) = dword_40121C + 1;
    if ( *((_WORD *)ModuleHandleA + 84) != 12287 )
      ExitProcess(0);
    HIWORD(v1) = HIWORD(ModuleHandleA);
    LOWORD(v1) = word_40122D + (_WORD)ModuleHandleA;
    LOWORD(i) = v1();
  }
  return (__int16)i;
}
// 401000: using guessed type int dword_401000;
// 40121C: using guessed type int dword_40121C;
// 40122D: using guessed type __int16 word_40122D;

//----- (00402567) --------------------------------------------------------
void sub_402567()
{
  int v0; // ebx
  int v1; // eax
  int v2; // edx
  int v3; // edx

  v0 = (unsigned __int8)byte_401040;
  LOWORD(v1) = TlsCallback_0();
  LOBYTE(v1) = v1 + 2;
  LOBYTE(dword_401055) = v1;
  wsprintfA((LPSTR)&dword_40121C + 1, "%i", ~(dword_401055 * (v1 + v2)));
  sub_4023B9(4198941);
  sub_4023DA(4198941);
  if ( *(_BYTE *)(v0 + 4198406) != ((unsigned __int8)byte_401221[v3] ^ 0xBE) )
    JUMPOUT(0x40234B);
  JUMPOUT(0x4022D8);
}
// 4025E8: control flows out of bounds to 40234B
// 4025F6: control flows out of bounds to 4022D8
// 4025FF: conditional instruction was optimized away because ecx.4==1
// 40259F: variable 'v1' is possibly undefined
// 40259F: variable 'v2' is possibly undefined
// 4025DD: variable 'v3' is possibly undefined
// 401040: using guessed type char byte_401040;
// 401055: using guessed type int dword_401055;
// 40121C: using guessed type int dword_40121C;

// nfuncs=9 queued=8 decompiled=8 lumina nreq=0 worse=0 better=0
// ALL OK, 8 function(s) have been successfully decompiled
