/* This file was generated by the Hex-Rays decompiler version 9.1.0.250226.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>

#include <stdarg.h>


//-------------------------------------------------------------------------
// Function declarations

void *sub_401000();
int __cdecl sub_401010(FILE *Stream, char *Format, _locale_t Locale, va_list ArgList); // idb
int sub_401040(char *Format, ...);
errno_t sub_401080();
_BYTE *__cdecl sub_401290(_BYTE *a1);
int __cdecl sub_4012E0(int a1);
int sub_401330();
int __cdecl sub_401390(int a1, int a2);
unsigned int __cdecl sub_4013B0(const char *a1);
_BYTE *sub_401430();
int __cdecl main(int argc, const char **argv, const char **envp);
int __cdecl sub_401820(char *Buffer, size_t BufferCount, char *Format, _locale_t Locale, va_list ArgList); // idb
int __cdecl sub_401880(char *Buffer, char *Format, _locale_t Locale, va_list ArgList); // idb
int sub_4018A0(char *Buffer, char *Format, ...);
BOOL sub_4018E0();
int sub_401900();
BOOL __stdcall TlsCallback_0(int a1, int a2, int a3);
// void __noreturn __report_rangecheckfailure(void); weak
int sub_401D7A();
int sub_401D82();
int __cdecl UserMathErrorFunction();
int sub_40220C();
void sub_402216();
char sub_402222();
void *sub_402249();
// int __scrt_initialize_default_local_stdio_options(void); weak
BOOL sub_40226C();
void *sub_402278();
void *sub_40227E();
LPTOP_LEVEL_EXCEPTION_FILTER sub_4023E6();
// LONG __stdcall __scrt_unhandled_exception_filter(struct _EXCEPTION_POINTERS *ExceptionInfo); idb
void sub_402448();
void sub_402450();
void __cdecl sub_40247C(); // idb
// int __cdecl set_new_mode(int NewMode);

//-------------------------------------------------------------------------
// Data declarations

// extern BOOL (__stdcall *CryptCreateHash)(HCRYPTPROV hProv, ALG_ID Algid, HCRYPTKEY hKey, DWORD dwFlags, HCRYPTHASH *phHash);
// extern BOOL (__stdcall *CryptHashData)(HCRYPTHASH hHash, const BYTE *pbData, DWORD dwDataLen, DWORD dwFlags);
// extern BOOL (__stdcall *CryptDestroyHash)(HCRYPTHASH hHash);
// extern BOOL (__stdcall *CryptGetHashParam)(HCRYPTHASH hHash, DWORD dwParam, BYTE *pbData, DWORD *pdwDataLen, DWORD dwFlags);
// extern BOOL (__stdcall *CryptReleaseContext)(HCRYPTPROV hProv, DWORD dwFlags);
// extern BOOL (__stdcall *CryptAcquireContextA)(HCRYPTPROV *phProv, LPCSTR szContainer, LPCSTR szProvider, DWORD dwProvType, DWORD dwFlags);
// extern BOOL (__stdcall *CloseHandle)(HANDLE hObject);
// extern HANDLE (__stdcall *CreateFileA)(LPCSTR lpFileName, DWORD dwDesiredAccess, DWORD dwShareMode, LPSECURITY_ATTRIBUTES lpSecurityAttributes, DWORD dwCreationDisposition, DWORD dwFlagsAndAttributes, HANDLE hTemplateFile);
// extern void (__stdcall *Sleep)(DWORD dwMilliseconds);
// extern BOOL (__stdcall *FindClose)(HANDLE hFindFile);
// extern BOOL (__stdcall *WriteFile)(HANDLE hFile, LPCVOID lpBuffer, DWORD nNumberOfBytesToWrite, LPDWORD lpNumberOfBytesWritten, LPOVERLAPPED lpOverlapped);
// extern BOOL (__stdcall *GetComputerNameA)(LPSTR lpBuffer, LPDWORD nSize);
// extern HANDLE (__stdcall *FindFirstFileA)(LPCSTR lpFileName, LPWIN32_FIND_DATAA lpFindFileData);
// extern void (__stdcall *InitializeSListHead)(PSLIST_HEADER ListHead);
// extern LPTOP_LEVEL_EXCEPTION_FILTER (__stdcall *SetUnhandledExceptionFilter)(LPTOP_LEVEL_EXCEPTION_FILTER lpTopLevelExceptionFilter);
// extern int (__cdecl *fflush)(FILE *Stream);
// extern FILE *(__cdecl *_acrt_iob_func)(unsigned int Ix);
// extern int (__cdecl *putchar)(int Character);
// extern int (__cdecl *fclose)(FILE *Stream);
// extern int (__cdecl *_stdio_common_vfprintf)(unsigned __int64 Options, FILE *Stream, const char *Format, _locale_t Locale, va_list ArgList);
// extern errno_t (__cdecl *fopen_s)(FILE **Stream, const char *FileName, const char *Mode);
// extern size_t (__cdecl *fwrite)(const void *Buffer, size_t ElementSize, size_t ElementCount, FILE *Stream);
// extern int (__cdecl *_stdio_common_vsprintf)(unsigned __int64 Options, char *Buffer, size_t BufferCount, const char *Format, _locale_t Locale, va_list ArgList);
_UNKNOWN unk_405480; // weak
int dword_40900C = 1; // weak
char off_409018[] = { '`', '1', '@', '\0' }; // idb
char Buffer[] = "0123456789ABCDEF0123456789ABCDEF"; // idb
DWORD nSize = 16u; // idb
int (*funcs_401A39[2])() = { &sub_4018E0, &sub_401900 }; // weak
DWORD pdwDataLen = 16u; // idb
union _SLIST_HEADER ListHead; // idb
_UNKNOWN unk_4093A0; // weak
int dword_4093A8; // weak
_UNKNOWN unk_4093B8; // weak
HCRYPTHASH hHash; // idb
BYTE pbData; // idb
BYTE byte_4093D4[16]; // weak
_UNKNOWN unk_4093E4; // weak
_UNKNOWN unk_4093E8; // weak


//----- (00401000) --------------------------------------------------------
void *sub_401000()
{
  return &unk_4093B8;
}

//----- (00401010) --------------------------------------------------------
int __cdecl sub_401010(FILE *Stream, char *Format, _locale_t Locale, va_list ArgList)
{
  unsigned __int64 *v4; // eax

  v4 = (unsigned __int64 *)sub_401000();
  return _stdio_common_vfprintf(*v4, Stream, Format, Locale, ArgList);
}

//----- (00401040) --------------------------------------------------------
int sub_401040(char *Format, ...)
{
  FILE *v1; // eax
  va_list va; // [esp+14h] [ebp+Ch] BYREF

  va_start(va, Format);
  v1 = _acrt_iob_func(1u);
  return sub_401010(v1, Format, 0, va);
}

//----- (00401080) --------------------------------------------------------
errno_t sub_401080()
{
  errno_t result; // eax
  char *v1; // [esp+20h] [ebp-144h]
  char *v2; // [esp+24h] [ebp-140h]
  char *v3; // [esp+28h] [ebp-13Ch]
  char *v4; // [esp+2Ch] [ebp-138h]
  char v6; // [esp+33h] [ebp-131h]
  FILE *Stream; // [esp+34h] [ebp-130h] BYREF
  char FileName[260]; // [esp+38h] [ebp-12Ch] BYREF
  char v9[20]; // [esp+13Ch] [ebp-28h] BYREF
  char v10[16]; // [esp+150h] [ebp-14h] BYREF

  strcpy(v9, "C:\\ReversingCTF\\");
  strcpy(v10, "AttackIRGC.dll");
  v1 = v9;
  v3 = FileName;
  do
  {
    v6 = *v1;
    *v3++ = *v1++;
  }
  while ( v6 );
  v4 = &v10[strlen(v10) + 1];
  v2 = (char *)&Stream + 3;
  while ( *++v2 )
    ;
  qmemcpy(v2, v10, v4 - v10);
  result = fopen_s(&Stream, FileName, "wb");
  if ( !result )
  {
    fwrite(&unk_405480, 1u, 0x2C00u, Stream);
    return fclose(Stream);
  }
  return result;
}

//----- (00401290) --------------------------------------------------------
_BYTE *__cdecl sub_401290(_BYTE *a1)
{
  _BYTE *result; // eax
  FILE *v2; // eax

  while ( 1 )
  {
    result = a1;
    if ( !*a1 )
      break;
    putchar((char)*a1++);
    v2 = _acrt_iob_func(1u);
    fflush(v2);
    Sleep(0xFu);
  }
  return result;
}

//----- (004012E0) --------------------------------------------------------
int __cdecl sub_4012E0(int a1)
{
  int v2; // [esp+0h] [ebp-4h]

  v2 = a1 % 3;
  if ( !(a1 % 3) )
    return 2 * a1;
  if ( v2 == 1 )
    return a1 + 100;
  if ( v2 == 2 )
    return a1 - 50;
  return 0;
}

//----- (00401330) --------------------------------------------------------
int sub_401330()
{
  int v1; // [esp+0h] [ebp-Ch]
  int v2; // [esp+4h] [ebp-8h]
  int i; // [esp+8h] [ebp-4h]

  v2 = 123;
  for ( i = 0; i < 5; ++i )
    v2 ^= 7 * i;
  v1 = sub_4012E0(v2);
  sub_401430();
  return sub_401390(v2, v1);
}

//----- (00401390) --------------------------------------------------------
int __cdecl sub_401390(int a1, int a2)
{
  return (a2 & a1) + (a2 ^ a1) - (a2 | a1);
}

//----- (004013B0) --------------------------------------------------------
unsigned int __cdecl sub_4013B0(const char *a1)
{
  unsigned int result; // eax
  unsigned int i; // [esp+Ch] [ebp-8h]

  for ( i = 0; ; ++i )
  {
    result = i;
    if ( i >= strlen(a1) )
      break;
    a1[i] ^= 0x2Au;
    a1[i] ^= 0x2Au;
  }
  return result;
}

//----- (00401430) --------------------------------------------------------
_BYTE *sub_401430()
{
  HANDLE hFindFile; // [esp+1Ch] [ebp-2C8h]
  HANDLE hFile; // [esp+24h] [ebp-2C0h]
  char *v3; // [esp+28h] [ebp-2BCh]
  char *v4; // [esp+2Ch] [ebp-2B8h]
  CHAR *v5; // [esp+30h] [ebp-2B4h]
  char *v6; // [esp+34h] [ebp-2B0h]
  int i; // [esp+38h] [ebp-2ACh]
  DWORD nNumberOfBytesToWrite; // [esp+40h] [ebp-2A4h]
  char v10; // [esp+47h] [ebp-29Dh]
  _WIN32_FIND_DATAA FindFileData; // [esp+48h] [ebp-29Ch] BYREF
  DWORD NumberOfBytesWritten; // [esp+188h] [ebp-15Ch] BYREF
  CHAR FileName[260]; // [esp+18Ch] [ebp-158h] BYREF
  _BYTE Buffer[44]; // [esp+290h] [ebp-54h] BYREF
  char v15[20]; // [esp+2BCh] [ebp-28h] BYREF
  char v16[16]; // [esp+2D0h] [ebp-14h] BYREF

  strcpy(v15, "C:\\ReversingCTF\\");
  strcpy(v16, "DroneAttack.txt");
  v3 = v15;
  v5 = FileName;
  do
  {
    v10 = *v3;
    *v5++ = *v3++;
  }
  while ( v10 );
  v6 = &v16[strlen(v16) + 1];
  v4 = (char *)&NumberOfBytesWritten + 3;
  while ( *++v4 )
    ;
  qmemcpy(v4, v16, v6 - v16);
  hFindFile = FindFirstFileA(FileName, &FindFileData);
  if ( hFindFile == (HANDLE)-1 )
  {
    Sleep(0x7D0u);
    return sub_401290("Danger! Anti aircraft system is still operating\n");
  }
  else
  {
    Sleep(0x7D0u);
    sub_401290("Anti aircraft system located\nIntiating disable sequence\n\n");
    FindClose(hFindFile);
    hFile = CreateFileA(FileName, 0x40000000u, 0, 0, 2u, 0x80u, 0);
    if ( hFile == (HANDLE)-1 )
    {
      Sleep(0x7D0u);
      return sub_401290("Danger! Anti aircraft system found but something is wrong. it is not disabled\n");
    }
    else
    {
      NumberOfBytesWritten = 0;
      nNumberOfBytesToWrite = 0;
      for ( i = 0; i < 32; ++i )
      {
        Buffer[nNumberOfBytesToWrite++] = ::Buffer[i];
        if ( !((i + 1) % 4) && i != 31 )
          Buffer[nNumberOfBytesToWrite++] = 32;
      }
      if ( nNumberOfBytesToWrite >= 0x29 )
        __report_rangecheckfailure();
      Buffer[nNumberOfBytesToWrite] = 0;
      WriteFile(hFile, Buffer, nNumberOfBytesToWrite, &NumberOfBytesWritten, 0);
      CloseHandle(hFile);
      Sleep(0x7D0u);
      sub_401290(
        "Great job. Anti aircraft system is disabled\n"
        "\n"
        "Stage 2: You are a jet fighter pilot. The sky is clear. Your mission: release bombs on IRGC headquarters.\n"
        "To find them, use the cyber intelligence unit\n");
      return (_BYTE *)sub_401080();
    }
  }
}
// 401BF4: using guessed type void __noreturn __report_rangecheckfailure(void);

//----- (004017B0) --------------------------------------------------------
int __cdecl main(int argc, const char **argv, const char **envp)
{
  char v4[8]; // [esp+0h] [ebp-Ch] BYREF

  sub_401040("%s\n", *(const char **)off_409018);
  Sleep(0x7D0u);
  sub_401290(
    "Stage 1: You are a special operations expert.\n"
    "Your mission is to protect our pilots. Disable the anti aircraft system\n"
    "Oh, intelligence report says the enemy spread decoys, find the real target, fast!\n"
    "\n");
  strcpy(v4, "Radar");
  sub_4013B0(v4);
  sub_401330();
  return 0;
}

//----- (00401820) --------------------------------------------------------
int __cdecl sub_401820(char *Buffer, size_t BufferCount, char *Format, _locale_t Locale, va_list ArgList)
{
  _DWORD *v5; // eax
  unsigned __int64 v7; // [esp-1Ch] [ebp-24h]
  int v9; // [esp+4h] [ebp-4h]

  v5 = sub_401000();
  HIDWORD(v7) = v5[1];
  LODWORD(v7) = *v5 | 1;
  v9 = _stdio_common_vsprintf(v7, Buffer, BufferCount, Format, Locale, ArgList);
  if ( v9 >= 0 )
    return v9;
  else
    return -1;
}

//----- (00401880) --------------------------------------------------------
int __cdecl sub_401880(char *Buffer, char *Format, _locale_t Locale, va_list ArgList)
{
  return sub_401820(Buffer, 0xFFFFFFFF, Format, Locale, ArgList);
}

//----- (004018A0) --------------------------------------------------------
int sub_4018A0(char *Buffer, char *Format, ...)
{
  va_list va; // [esp+18h] [ebp+10h] BYREF

  va_start(va, Format);
  return sub_401880(Buffer, Format, 0, va);
}

//----- (004018E0) --------------------------------------------------------
BOOL sub_4018E0()
{
  return GetComputerNameA((LPSTR)&pbData, &nSize);
}

//----- (00401900) --------------------------------------------------------
int sub_401900()
{
  int result; // eax
  DWORD i; // [esp+Ch] [ebp-Ch]

  CryptHashData(hHash, &pbData, strlen((const char *)&pbData), 0);
  result = CryptGetHashParam(hHash, 2u, byte_4093D4, &pdwDataLen, 0);
  for ( i = 0; i < pdwDataLen; ++i )
    result = sub_4018A0(&Buffer[2 * i], "%02X", byte_4093D4[i]);
  Buffer[32] = 0;
  return result;
}
// 401BF4: using guessed type void __noreturn __report_rangecheckfailure(void);
// 4093D4: using guessed type BYTE byte_4093D4[16];

//----- (004019D0) --------------------------------------------------------
BOOL __stdcall TlsCallback_0(int a1, int a2, int a3)
{
  BOOL result; // eax
  unsigned int i; // [esp+4h] [ebp-10h]
  int j; // [esp+8h] [ebp-Ch]
  HCRYPTPROV phProv; // [esp+Ch] [ebp-8h] BYREF

  if ( a2 == 1 )
  {
    CryptAcquireContextA(&phProv, 0, 0, 1u, 0xF0000000);
    CryptCreateHash(phProv, 0x8003u, 0, 0, &hHash);
    for ( i = 0; i < 2; ++i )
      funcs_401A39[i]();
    for ( j = 0; j < 16; ++j )
      sub_4018A0(&Buffer[2 * j], "%02X", byte_4093D4[j]);
    Buffer[32] = 0;
    CryptDestroyHash(hHash);
    return CryptReleaseContext(phProv, 0);
  }
  return result;
}
// 401BF4: using guessed type void __noreturn __report_rangecheckfailure(void);
// 409044: using guessed type int (*funcs_401A39[2])();
// 4093D4: using guessed type BYTE byte_4093D4[16];

//----- (00401D7A) --------------------------------------------------------
int sub_401D7A()
{
  __scrt_initialize_default_local_stdio_options();
  return 0;
}
// 40224F: using guessed type int __scrt_initialize_default_local_stdio_options(void);

//----- (00401D82) --------------------------------------------------------
int sub_401D82()
{
  int v0; // eax

  sub_4023E6();
  v0 = UserMathErrorFunction();
  return set_new_mode(v0);
}

//----- (00402209) --------------------------------------------------------
int __cdecl UserMathErrorFunction()
{
  return 0;
}

//----- (0040220C) --------------------------------------------------------
int sub_40220C()
{
  return 1;
}

//----- (00402216) --------------------------------------------------------
void sub_402216()
{
  InitializeSListHead(&ListHead);
}

//----- (00402222) --------------------------------------------------------
char sub_402222()
{
  return 1;
}

//----- (00402249) --------------------------------------------------------
void *sub_402249()
{
  return &unk_4093A0;
}

//----- (0040226C) --------------------------------------------------------
BOOL sub_40226C()
{
  return dword_40900C == 0;
}
// 40900C: using guessed type int dword_40900C;

//----- (00402278) --------------------------------------------------------
void *sub_402278()
{
  return &unk_4093E8;
}

//----- (0040227E) --------------------------------------------------------
void *sub_40227E()
{
  return &unk_4093E4;
}

//----- (004023E6) --------------------------------------------------------
LPTOP_LEVEL_EXCEPTION_FILTER sub_4023E6()
{
  return SetUnhandledExceptionFilter(__scrt_unhandled_exception_filter);
}

//----- (00402448) --------------------------------------------------------
void sub_402448()
{
  dword_4093A8 = 0;
}
// 4093A8: using guessed type int dword_4093A8;

//----- (00402450) --------------------------------------------------------
void sub_402450()
{
  ;
}
// 402450: could not find valid save-restore pair for edi

//----- (0040247C) --------------------------------------------------------
void __cdecl sub_40247C()
{
  ;
}
// 40247C: could not find valid save-restore pair for edi

// nfuncs=91 queued=31 decompiled=31 lumina nreq=0 worse=0 better=0
// ALL OK, 31 function(s) have been successfully decompiled
