/* This file was generated by the Hex-Rays decompiler version 9.1.0.250226.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>

#include <stdarg.h>


//-------------------------------------------------------------------------
// Function declarations

void *sub_401000();
void *sub_401010();
int __cdecl sub_401020(FILE *Stream, char *Format, _locale_t Locale, va_list ArgList); // idb
int __cdecl sub_401050(FILE *Stream, char *Format, _locale_t Locale, va_list Arglist); // idb
int sub_401080();
int level_0();
int level_1();
int level_2();
int level_3();
int __cdecl level_3_check_input(unsigned int16_t *a1);
int level_4();
int level_5();
BOOL __cdecl level_5_check(int a1);
int level_6();
int __cdecl sub_401910(_BYTE *a1);
size_t __cdecl sub_401950(char *Str);
int level_7();
_UNKNOWN ****__cdecl sub_401A80(_BYTE *a1);
int level_8();
int __cdecl sub_401BD0(_BYTE *a1);
BOOL __cdecl sub_401C30(char *Str);
int __fastcall level_9(int a1);
int __cdecl main(int argc, const char **argv, const char **envp);
int printf(char *Format, ...);
int __cdecl sub_401E00(int a1);
int scanf(char *Format, ...);
int __cdecl sub_401EF0(int a1);
int sub_402060();
int sub_402068();
int __cdecl UserMathErrorFunction();
int sub_4024F2();
void sub_4024FC();
char sub_402508();
// int __scrt_initialize_default_local_stdio_options(void); weak
BOOL sub_40254C();
void *sub_402558();
void *sub_40255E();
LPTOP_LEVEL_EXCEPTION_FILTER sub_4026C6();
// LONG __stdcall __scrt_unhandled_exception_filter(struct _EXCEPTION_POINTERS *ExceptionInfo); idb
void sub_402728();
void sub_402730();
void __cdecl sub_40275C(); // idb
// void *__cdecl memset(void *, int Val, size_t Size);
// char *__cdecl strchr(const char *Str, int Val);
// char *__cdecl strcat(char *Destination, const char *Source);
// char *__cdecl strcpy(char *Destination, const char *Source);
// size_t __cdecl strlen(const char *Str);
// int __cdecl set_new_mode(int NewMode);

//-------------------------------------------------------------------------
// Data declarations

// extern LSTATUS (__stdcall *RegSetValueExW)(HKEY hKey, LPCWSTR lpValueName, DWORD Reserved, DWORD dwType, const BYTE *lpData, DWORD cbData);
// extern LSTATUS (__stdcall *RegQueryValueExW)(HKEY hKey, LPCWSTR lpValueName, LPDWORD lpReserved, LPDWORD lpType, LPBYTE lpData, LPDWORD lpcbData);
// extern LSTATUS (__stdcall *RegCreateKeyExW)(HKEY hKey, LPCWSTR lpSubKey, DWORD Reserved, LPWSTR lpClass, DWORD dwOptions, REGSAM samDesired, const LPSECURITY_ATTRIBUTES lpSecurityAttributes, PHKEY phkResult, LPDWORD lpdwDisposition);
// extern BOOL (__stdcall *CloseHandle)(HANDLE hObject);
// extern BOOL (__stdcall *ReadFile)(HANDLE hFile, LPVOID lpBuffer, DWORD nNumberOfBytesToRead, LPDWORD lpNumberOfBytesRead, LPOVERLAPPED lpOverlapped);
// extern HANDLE (__stdcall *CreateFileA)(LPCSTR lpFileName, DWORD dwDesiredAccess, DWORD dwShareMode, LPSECURITY_ATTRIBUTES lpSecurityAttributes, DWORD dwCreationDisposition, DWORD dwFlagsAndAttributes, HANDLE hTemplateFile);
// extern LPTOP_LEVEL_EXCEPTION_FILTER (__stdcall *SetUnhandledExceptionFilter)(LPTOP_LEVEL_EXCEPTION_FILTER lpTopLevelExceptionFilter);
// extern void (__stdcall *InitializeSListHead)(PSLIST_HEADER ListHead);
// extern FILE *(__cdecl *_acrt_iob_func)(unsigned int Ix);
// extern int (__cdecl *_stdio_common_vfscanf)(unsigned __int64 Options, FILE *Stream, const char *Format, _locale_t Locale, va_list Arglist);
// extern char *(__cdecl *fgets)(char *Buffer, int MaxCount, FILE *Stream);
// extern int (__cdecl *_stdio_common_vfprintf)(unsigned __int64 Options, FILE *Stream, const char *Format, _locale_t Locale, va_list ArgList);
// extern int (__cdecl *strncmp)(const char *Str1, const char *Str2, size_t MaxCount);
int16_t level_3_array[8] = { 7, 33, 1, -600, -5000, 1777, 13, 69 }; // weak
char *Str = "###################O####...########.##...#.########.##.###.########....###...X##################"; // idb
_UNKNOWN ****off_404090[2] = { &off_4040C0, &off_40409C }; // weak
int dword_4041F8[20] =
{
  899096851,
  -1742828873,
  53389049,
  329515568,
  1059620498,
  312546320,
  -101834289,
  313164324,
  1849813186,
  -691702435,
  -764295860,
  269903603,
  -1699763439,
  -1530414447,
  1307723969,
  -1492427407,
  390599349,
  1401854275,
  596464835,
  2041641142
}; // weak
WCHAR SubKey[] = L"Software\\CyberCourse\\Ex12"; // idb
char Format[] = "ERROR - Can't get current level registry key!!"; // idb
WCHAR ValueName[] = L"CurrentLevel"; // idb
WCHAR aCurrentlevel_0[] = L"CurrentLevel"; // idb
char aErrorCanTCreat[] = "ERROR - Can't create current level registry value!!"; // idb
WCHAR aSoftwareCyberc_0[] = L"Software\\CyberCourse\\Ex12"; // idb
char aErrorCanTGetCu_0[] = "ERROR - Can't get current level registry key!!"; // idb
WCHAR aCurrentlevel_1[] = L"CurrentLevel"; // idb
WCHAR aCurrentlevel_2[] = L"CurrentLevel"; // idb
char aErrorCanTSetCr[] = "ERROR - Can't set/create current level registry value!!"; // idb
char aWrongPassword[] = "Wrong password!\r\n"; // idb
char aToEnterWonderl[] = "To enter Wonderland, you must know the password!\r\n(Please input a password)\r\n"; // idb
char Source[] = "All "; // idb
char aHail[] = "Hail "; // idb
char aThe[] = "The "; // idb
char aQueen[] = "Queen!"; // idb
char aWrongTryAgain[] = "\r\nWrong! Try again...\r\n"; // idb
char aCorrect[] = "\r\nCorrect!\r\n"; // idb
char aGreatNowTellMe[] = "Great. Now tell me the second password.\r\n(Please enter the password)\r\n"; // idb
char aIntoTheRabbitH[21] = "into the rabbit hole"; // weak
char aCorrectYouMayE[] = "Correct! you may enter..\r\n"; // idb
char aWrongPassword_0[] = "Wrong password!\r\n"; // idb
char aYouKnowWhatTha[] = "You know what? That was too easy. *Now* tell me the second password.\r\n(Please enter the password)\r\n"; // idb
char aIntoTheRabbitH_0[21] = "into the rabbit hole"; // weak
char aCorrectYouMayE_0[] = "Correct! you may enter..\r\n"; // idb
char aWaitCanYouHelp[] = "..Wait! Can you help me first with something?\r\n(Enter the correct numbers)\r\n"; // idb
char aBadOrInvalidNu[] = "Bad or invalid numbers! Try again from the start..\r\n"; // idb
char aWrongTryAgain_0[] = "Wrong! Try again.\r\n"; // idb
char aThanksForTheHe[] = "Thanks for the help! You may enter now.\r\n"; // idb
char aWaitIHaveSomet[] = "Wait... I have something on the tip of my tongue!\r\n(Enter the correct number)\r\n"; // idb
char aErrorBadInputT[] = "Error - bad input. Try again.\r\n"; // idb
char aWrong[] = "Wrong!\r\n"; // idb
char aCheaterTryAgai[] = "Cheater.. Try again another way.\r\n"; // idb
char aYeahGoodLuckAn[] = "Yeah! Good luck!! (and good job!)\r\n"; // idb
char aWrong_0[] = "Wrong!\r\n"; // idb
char aYouMayEnterBut[] = "You may enter, but can you find the Queen's palace?...\r\n(You're not a noob by now. Figure it out on your own.)\r\n"; // idb
char aError[] = "ERROR!\r\n"; // idb
char aYouAreLost[] = "You are lost!\r\n"; // idb
char aYouHaveFoundTh[] = "You have found the Queen's palace!\r\n"; // idb
char aHelloIMTheRabb[] = "Hello! I'm the rabbit, and to get around here, you're gonna need to know the language. Let's try speaking.\r\n(type in the correct string)\r\n"; // idb
char a01011010[12] = "01 01 10 10"; // weak
char aThatSWrong[] = "That's wrong.\r\n"; // idb
char aCorrect_0[] = "Correct!\r\n"; // idb
char aTheQueenSRoom[] = "The Queen's Room"; // idb
char aYouMustWalkThr[] = "You must walk through the Queen's mansion to find the right room, with the Queen in it.\r\n(Solve.)\r\n"; // idb
char Str2[] = "The Queen's Room"; // idb
char aYouReLostTryAg[] = "You're lost. Try again.\r\n"; // idb
char aYouVeFoundTheQ[] = "You've found the Queen!\r\n"; // idb
char aHelloIAmTheQue[] = "Hello! I am the Queen, and it is said you are a great wizard, capable of conjuring fire with a single word.Please, show me your skills.\r\n(Please input a valid 'magic word'.)\r\n"; // idb
char aThisIsLazyIExc[] = "This is lazy; I except much more impressive words. Try again.\r\n"; // idb
char aIMSorryIDidnTU[] = "I'm sorry, I didn't understand. Try again.\r\n"; // idb
char aAlmostThereTry[] = "Almost there! Try again.\r\n"; // idb
char aWellDone[] = "Well done!\r\n"; // idb
char aWoahYouTrulyAr[] = "Woah!! You truly are amazing! Now, let me riddle you something that ought to befuddle you.\r\n(Solve.)\r\n"; // idb
char aNotANumber[] = "Not a number!\r\n"; // idb
char aWrong_1[] = "Wrong!\r\n"; // idb
char aYouAreQuiteCle[] = "You are quite clever! Good job!\r\n"; // idb
char aThereIsNoSuchL[] = "There is no such level!\r\n"; // idb
char aBadLevelNumber[] = "Bad level number.\r\n"; // idb
char aYouHavenTUnloc[] = "You haven't unlocked this level yet.\r\n"; // idb
char asc_404C68[] = "\r\n\r\n"; // idb
int dword_404C74 = 1; // weak
union _SLIST_HEADER ListHead = { 0uLL }; // idb
int dword_404CC0 = 0; // weak
_UNKNOWN unk_404FF0; // weak
_UNKNOWN unk_404FF8; // weak
_UNKNOWN unk_405000; // weak
_UNKNOWN unk_405004; // weak


//----- (00401000) --------------------------------------------------------
void *sub_401000()
{
  return &unk_404FF8;
}

//----- (00401010) --------------------------------------------------------
void *sub_401010()
{
  return &unk_404FF0;
}

//----- (00401020) --------------------------------------------------------
int __cdecl sub_401020(FILE *Stream, char *Format, _locale_t Locale, va_list ArgList)
{
  unsigned __int64 *v4; // eax

  v4 = (unsigned __int64 *)sub_401000();
  return _stdio_common_vfprintf(*v4, Stream, Format, Locale, ArgList);
}

//----- (00401050) --------------------------------------------------------
int __cdecl sub_401050(FILE *Stream, char *Format, _locale_t Locale, va_list Arglist)
{
  unsigned __int64 *v4; // eax

  v4 = (unsigned __int64 *)sub_401010();
  return _stdio_common_vfscanf(*v4, Stream, Format, Locale, Arglist);
}

//----- (00401080) --------------------------------------------------------
int sub_401080()
{
  DWORD Type; // [esp+0h] [ebp-14h] BYREF
  LSTATUS v2; // [esp+4h] [ebp-10h]
  HKEY phkResult; // [esp+8h] [ebp-Ch] BYREF
  DWORD cbData; // [esp+Ch] [ebp-8h] BYREF
  BYTE Data[4]; // [esp+10h] [ebp-4h] BYREF

  if ( RegCreateKeyExW(HKEY_CURRENT_USER, SubKey, 0, 0, 0, 0xF003Fu, 0, &phkResult, 0) )
  {
    printf(Format);
    return -1;
  }
  else
  {
    *(_DWORD *)Data = 0;
    cbData = 4;
    v2 = RegQueryValueExW(phkResult, ValueName, 0, &Type, Data, &cbData);
    if ( v2 != 2 && cbData == 4 && Type == 4 )
      return *(_DWORD *)Data;
    *(_DWORD *)Data = 0;
    if ( !RegSetValueExW(phkResult, aCurrentlevel_0, 0, 4u, Data, 4u) )
    {
      return *(_DWORD *)Data;
    }
    else
    {
      printf(aErrorCanTCreat);
      return -1;
    }
  }
}

//----- (00401140) --------------------------------------------------------
int level_0()
{
  FILE *v0; // eax
  size_t v1; // eax
  char Buffer[1024]; // [esp+0h] [ebp-800h] BYREF
  char Destination[1024]; // [esp+400h] [ebp-400h] BYREF

  printf(aToEnterWonderl);
  while ( 1 )
  {
    v0 = _acrt_iob_func(0);
    fgets(Buffer, 1023, v0);
    strcpy(Destination, Source);
    strcat(Destination, aHail);
    strcat(Destination, aThe);
    strcat(Destination, aQueen);
    v1 = strlen(Destination);
    if ( !strncmp(Buffer, Destination, v1) )
      break;
    printf(aWrongTryAgain);
  }
  return printf(aCorrect);
}

//----- (00401230) --------------------------------------------------------
int level_1()
{
  FILE *v0; // eax
  size_t v1; // eax
  char Buffer[1024]; // [esp+0h] [ebp-40Ch] BYREF
  size_t v4; // [esp+400h] [ebp-Ch]
  char *Str; // [esp+404h] [ebp-8h]
  size_t i; // [esp+408h] [ebp-4h]

  printf(aGreatNowTellMe);
  while ( 1 )
  {
    memset(Buffer, 0, sizeof(Buffer));
    v0 = _acrt_iob_func(0);
    fgets(Buffer, 1023, v0);
    v4 = strlen(Buffer);
    for ( i = 0; i < v4; ++i )
      Buffer[i] ^= 0xAu;
    Str = aIntoTheRabbitH;
    v1 = strlen(aIntoTheRabbitH);
    if ( !strncmp(Buffer, aIntoTheRabbitH, v1) )
      break;
    printf(aWrongPassword);
  }
  return printf(aCorrectYouMayE);
}

//----- (00401330) --------------------------------------------------------
int level_2()
{
  FILE *v0; // eax
  size_t v1; // eax
  char Buffer[1024]; // [esp+0h] [ebp-40Ch] BYREF
  size_t v4; // [esp+400h] [ebp-Ch]
  char *Str; // [esp+404h] [ebp-8h]
  int i; // [esp+408h] [ebp-4h]

  printf(aYouKnowWhatTha);
  while ( 1 )
  {
    memset(Buffer, 0, sizeof(Buffer));
    v0 = _acrt_iob_func(0);
    fgets(Buffer, 1023, v0);
    v4 = strlen(Buffer);
    for ( i = 0; i + 3 < v4; i += 4 )
      *(_DWORD *)&Buffer[i] ^= 0x41524241u;
    Str = aIntoTheRabbitH_0;
    v1 = strlen(aIntoTheRabbitH_0);
    if ( !strncmp(Buffer, aIntoTheRabbitH_0, v1) )
      break;
    printf(aWrongPassword_0);
  }
  return printf(aCorrectYouMayE_0);
}

//----- (00401430) --------------------------------------------------------
int level_3()
{
  unsigned int16_t v1[8]; // [esp+0h] [ebp-18h] BYREF
  int v2; // [esp+10h] [ebp-8h]
  int i; // [esp+14h] [ebp-4h]

  printf(aWaitCanYouHelp);
  while ( 1 )
  {
    do
    {
      v2 = 0;
      for ( i = 0; i < 8; ++i )
      {
        if ( scanf(" %hu", &v1[i]) != 1 || v1[i] >= 8u )
        {
          printf(aBadOrInvalidNu);
          v2 = 1;
          break;
        }
      }
    }
    while ( v2 == 1 );
    if ( level_3_check_input(v1) )
      return printf(aThanksForTheHe);
    printf(aWrongTryAgain_0);
  }
}

//----- (004014F0) --------------------------------------------------------
int __cdecl level_3_check_input(unsigned int16_t *a1)
{
  unsigned int i; // [esp+0h] [ebp-Ch]
  int16_t v3; // [esp+4h] [ebp-8h]

  v3 = level_3_array[*a1];
  for ( i = 1; i < 8; ++i )
  {
    if ( level_3_array[a1[i]] <= v3 )
      return 0;
    v3 = level_3_array[a1[i]];
  }
  return 1;
}
// 404000: using guessed type int16_t level_3_array[8];

//----- (00401570) --------------------------------------------------------
int level_4()
{
  size_t v0; // eax
  char Str[12]; // [esp+0h] [ebp-10h] BYREF
  char *Str1; // [esp+Ch] [ebp-4h] BYREF

  printf(aWaitIHaveSomet);
  while ( 1 )
  {
    while ( 1 )
    {
        // Put into Str1 the address of a string
      while ( scanf(" %du", &Str1) != 1 )
        printf(aErrorBadInputT);
      strcpy(Str, "Good luck!!");
      v0 = strlen(Str);
      // check if Str1 and Str are equal
      if ( !strncmp(Str1, Str, v0) )
        break;
      printf(aWrong);
    }
    if ( Str1 != Str )
      break;
    printf(aCheaterTryAgai);
  }
  return printf(aYeahGoodLuckAn);
}

//----- (00401650) --------------------------------------------------------
int level_5()
{
  FILE *v0; // eax
  char v2[1024]; // [esp+0h] [ebp-808h] BYREF
  char Buffer[1024]; // [esp+400h] [ebp-408h] BYREF
  DWORD NumberOfBytesRead; // [esp+800h] [ebp-8h] BYREF
  HANDLE hFile; // [esp+804h] [ebp-4h]

  printf(aYouMayEnterBut);
  while ( 1 )
  {
    while ( 1 )
    {
      while ( 1 )
      {
        v0 = _acrt_iob_func(0);
        fgets(Buffer, 1023, v0);
        v2[strlen(Buffer) + 1023] = 0;
        hFile = CreateFileA(Buffer, 0x80000000, 1u, 0, 3u, 0x80u, 0);
        if ( hFile != (HANDLE)-1 )
          break;
        printf(aWrong_0);
      }
      NumberOfBytesRead = 0;
      if ( ReadFile(hFile, v2, 0x400u, &NumberOfBytesRead, 0) )
        break;
      printf(aError);
      CloseHandle(hFile);
    }
    CloseHandle(hFile);
    if ( level_5_check((int)v2) )
      break;
    printf(aYouAreLost);
  }
  return printf(aYouHaveFoundTh);
}

//----- (00401770) --------------------------------------------------------
BOOL __cdecl level_5_check(int a1)
{
  int v2; // [esp+4h] [ebp-Ch]
  char *v3; // [esp+Ch] [ebp-4h]

  v3 = strchr(Str, 79); // "O"
  v2 = 0;
  while ( 2 )
  {
    switch ( *(_BYTE *)(v2 + a1) )
    {
      case '1':
        ++v3;
        goto LABEL_8;
      case '2':
        v3 += 16;
        goto LABEL_8;
      case '3':
        --v3;
        goto LABEL_8;
      case '4':
        v3 -= 16;
LABEL_8:
        if ( *(_BYTE *)(++v2 + a1) && *v3 == 46 )
          continue;
        return *v3 == 88;
      default:
        return 0;
    }
  }
}

//----- (00401840) --------------------------------------------------------
int level_6()
{
  FILE *v0; // eax
  size_t v1; // eax
  char Buffer[1024]; // [esp+2h] [ebp-404h] BYREF
  char *Str; // [esp+402h] [ebp-4h]

  printf(aHelloIMTheRabb);
  while ( 1 )
  {
    v0 = _acrt_iob_func(0);
    fgets(Buffer, 1023, v0);
    Buffer[strlen(Buffer) - 1] = 0;
    sub_401910(Buffer);
    sub_401950(Buffer);
    Str = a01011010;
    v1 = strlen(a01011010);
    if ( !strncmp(Buffer, a01011010, v1) )
      break;
    printf(aThatSWrong);
  }
  return printf(aCorrect_0);
}

//----- (00401910) --------------------------------------------------------
int __cdecl sub_401910(_BYTE *a1)
{
  int result; // eax

  while ( 1 )
  {
    result = (char)*a1;
    if ( !*a1 )
      break;
    *a1 = (*a1 + 78) ^ 0xAA;
    ++a1;
  }
  return result;
}

//----- (00401950) --------------------------------------------------------
size_t __cdecl sub_401950(char *Str)
{
  size_t result; // eax
  signed int v2; // [esp+0h] [ebp-Ch]
  signed int i; // [esp+4h] [ebp-8h]
  char v4; // [esp+Ah] [ebp-2h]
  char v5; // [esp+Bh] [ebp-1h]

  result = strlen(Str);
  v2 = result;
  v5 = Str[result - 1] & 0x1F;
  for ( i = 0; i < v2; ++i )
  {
    v4 = Str[i] & 0x1F;
    Str[i] = (Str[i] >> 5) + 8 * v5;
    v5 = v4;
    result = i + 1;
  }
  return result;
}

//----- (004019D0) --------------------------------------------------------
int level_7()
{
  FILE *v0; // eax
  size_t v1; // eax
  char Buffer[1024]; // [esp+0h] [ebp-404h] BYREF
  char *Str1; // [esp+400h] [ebp-4h]

  printf(aYouMustWalkThr);
  while ( 1 )
  {
    v0 = _acrt_iob_func(0);
    fgets(Buffer, 1023, v0);
    Str1 = (char *)sub_401A80(Buffer);
    if ( Str1 )
    {
      v1 = strlen(aTheQueenSRoom);
      if ( !strncmp(Str1, Str2, v1) )
        break;
    }
    printf(aYouReLostTryAg);
  }
  return printf(aYouVeFoundTheQ);
}

//----- (00401A80) --------------------------------------------------------
_UNKNOWN ****__cdecl sub_401A80(_BYTE *a1)
{
  _UNKNOWN *****v3; // [esp+8h] [ebp-4h]

  v3 = off_404090;
  while ( *a1 )
  {
    if ( *a1 == 76 )
    {
      v3 = (_UNKNOWN *****)v3[1];
    }
    else
    {
      if ( *a1 != 82 )
        return 0;
      v3 = (_UNKNOWN *****)*v3;
    }
    ++a1;
  }
  return v3[2];
}
// 404090: using guessed type _UNKNOWN ****off_404090[2];

//----- (00401AF0) --------------------------------------------------------
int level_8()
{
  FILE *v0; // eax
  char Buffer[1024]; // [esp+0h] [ebp-400h] BYREF

  printf(aHelloIAmTheQue);
  while ( 1 )
  {
    while ( 1 )
    {
      while ( 1 )
      {
        memset(Buffer, 0, sizeof(Buffer));
        v0 = _acrt_iob_func(0);
        fgets(Buffer, 1020, v0);
        if ( strlen(Buffer) >= 0x1E )
          break;
        printf(aThisIsLazyIExc);
      }
      if ( sub_401BD0(Buffer) )
        break;
      printf(aIMSorryIDidnTU);
    }
    if ( sub_401C30(Buffer) )
      break;
    printf(aAlmostThereTry);
  }
  return printf(aWellDone);
}

//----- (00401BD0) --------------------------------------------------------
int __cdecl sub_401BD0(_BYTE *a1)
{
  while ( *a1 )
  {
    if ( (char)*a1 < 97 || (char)*a1 > 122 )
      return 0;
    if ( ((char)*a1 - 97) % 3 )
      return 0;
    ++a1;
  }
  return 1;
}

//----- (00401C30) --------------------------------------------------------
BOOL __cdecl sub_401C30(char *Str)
{
  int v2; // [esp+4h] [ebp-8h]
  char *i; // [esp+8h] [ebp-4h]

  if ( strlen(Str) % 4 )
    return 0;
  v2 = 0;
  for ( i = Str; *(_DWORD *)i; i += 4 )
    v2 ^= *(_DWORD *)i;
  return v2 == 1970760046;
}

//----- (00401CA0) --------------------------------------------------------
int __fastcall level_9(int a1)
{
  char v2[4]; // [esp+0h] [ebp-4h] BYREF

  *(_DWORD *)v2 = a1;
  printf(aWoahYouTrulyAr);
  while ( 1 )
  {
    while ( scanf(" %d", v2) != 1 )
      printf(aNotANumber);
    if ( dword_4041F8[*(_DWORD *)v2] == 1735289210 )
      break;
    printf(aWrong_1);
  }
  return printf(aYouAreQuiteCle);
}
// 4041F8: using guessed type int dword_4041F8[20];

//----- (00401D20) --------------------------------------------------------
int __cdecl main(int argc, const char **argv, const char **envp)
{
  int v4; // [esp+0h] [ebp-8h]
  char v5[4]; // [esp+4h] [ebp-4h] BYREF

  while ( 1 )
  {
    v4 = sub_401080();
    printf(
      "Welcome to Wonderland. I am the mad hatter, and I have some riddles for you...\r\n"
      "Input a level number (latest level- %d):\r\n",
      v4);
    if ( scanf(" %d", v5) )
    {
      if ( *(int *)v5 <= v4 )
      {
        printf(asc_404C68);
        if ( sub_401E00(*(int *)v5) )
          sub_401EF0(*(_DWORD *)v5 + 1);
      }
      else
      {
        printf(aYouHavenTUnloc);
      }
    }
    else
    {
      printf(aBadLevelNumber);
    }
  }
}

//----- (00401DC0) --------------------------------------------------------
int printf(char *Format, ...)
{
  FILE *v1; // eax
  va_list va; // [esp+14h] [ebp+Ch] BYREF

  va_start(va, Format);
  v1 = _acrt_iob_func(1u);
  return sub_401020(v1, Format, 0, va);
}

//----- (00401E00) --------------------------------------------------------
int __cdecl sub_401E00(int a1)
{
  int result; // eax

  switch ( a1 )
  {
    case 0:
      level_0();
      goto LABEL_12;
    case 1:
      level_1();
      goto LABEL_12;
    case 2:
      level_2();
      goto LABEL_12;
    case 3:
      level_3();
      goto LABEL_12;
    case 4:
      level_4();
      goto LABEL_12;
    case 5:
      level_5();
      goto LABEL_12;
    case 6:
      level_6();
      goto LABEL_12;
    case 7:
      level_7();
      goto LABEL_12;
    case 8:
      level_8();
      goto LABEL_12;
    case 9:
      level_9(a1);
LABEL_12:
      result = 1;
      break;
    default:
      printf(aThereIsNoSuchL);
      result = 0;
      break;
  }
  return result;
}

//----- (00401EB0) --------------------------------------------------------
int scanf(char *Format, ...)
{
  FILE *v1; // eax
  va_list va; // [esp+14h] [ebp+Ch] BYREF

  va_start(va, Format);
  v1 = _acrt_iob_func(0);
  return sub_401050(v1, Format, 0, va);
}

//----- (00401EF0) --------------------------------------------------------
int __cdecl sub_401EF0(int a1)
{
  DWORD Type; // [esp+4h] [ebp-10h] BYREF
  DWORD cbData; // [esp+8h] [ebp-Ch] BYREF
  HKEY phkResult; // [esp+Ch] [ebp-8h] BYREF
  BYTE Data[4]; // [esp+10h] [ebp-4h] BYREF

  if ( RegCreateKeyExW(HKEY_CURRENT_USER, aSoftwareCyberc_0, 0, 0, 0, 0xF003Fu, 0, &phkResult, 0) )
  {
    printf(aErrorCanTGetCu_0);
    return 0;
  }
  else
  {
    *(_DWORD *)Data = 0;
    cbData = 4;
    Type = 0;
    if ( RegQueryValueExW(phkResult, aCurrentlevel_1, 0, &Type, Data, &cbData) == 2 || *(int *)Data < a1 )
    {
      *(_DWORD *)Data = a1;
      if ( RegSetValueExW(phkResult, aCurrentlevel_2, 0, 4u, Data, 4u) )
      {
        printf(aErrorCanTSetCr);
        return 0;
      }
      else
      {
        return 1;
      }
    }
    else
    {
      return 0;
    }
  }
}

//----- (00402060) --------------------------------------------------------
int sub_402060()
{
  __scrt_initialize_default_local_stdio_options();
  return 0;
}
// 40252F: using guessed type int __scrt_initialize_default_local_stdio_options(void);

//----- (00402068) --------------------------------------------------------
int sub_402068()
{
  int v0; // eax

  sub_4026C6();
  v0 = UserMathErrorFunction();
  return set_new_mode(v0);
}

//----- (004024EF) --------------------------------------------------------
int __cdecl UserMathErrorFunction()
{
  return 0;
}

//----- (004024F2) --------------------------------------------------------
int sub_4024F2()
{
  return 1;
}

//----- (004024FC) --------------------------------------------------------
void sub_4024FC()
{
  InitializeSListHead(&ListHead);
}

//----- (00402508) --------------------------------------------------------
char sub_402508()
{
  return 1;
}

//----- (0040254C) --------------------------------------------------------
BOOL sub_40254C()
{
  return dword_404C74 == 0;
}
// 404C74: using guessed type int dword_404C74;

//----- (00402558) --------------------------------------------------------
void *sub_402558()
{
  return &unk_405004;
}

//----- (0040255E) --------------------------------------------------------
void *sub_40255E()
{
  return &unk_405000;
}

//----- (004026C6) --------------------------------------------------------
LPTOP_LEVEL_EXCEPTION_FILTER sub_4026C6()
{
  return SetUnhandledExceptionFilter(__scrt_unhandled_exception_filter);
}

//----- (00402728) --------------------------------------------------------
void sub_402728()
{
  dword_404CC0 = 0;
}
// 404CC0: using guessed type int dword_404CC0;

//----- (00402730) --------------------------------------------------------
void sub_402730()
{
  ;
}
// 402730: could not find valid save-restore pair for edi

//----- (0040275C) --------------------------------------------------------
void __cdecl sub_40275C()
{
  ;
}
// 40275C: could not find valid save-restore pair for edi

// nfuncs=103 queued=40 decompiled=40 lumina nreq=0 worse=0 better=0
// ALL OK, 40 function(s) have been successfully decompiled
