/* This file was generated by the Hex-Rays decompiler version 9.1.0.250226.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>

#include <stdarg.h>


//-------------------------------------------------------------------------
// Function declarations

int __cdecl main(int argc, const char **argv, const char **envp);
int __cdecl user_defined(int a1);
void *sub_4010D0();
int __cdecl sub_4010E0(FILE *Stream, char *Format, _locale_t Locale, va_list ArgList); // idb
int printf_like(char *Format, ...);
void *sub_401150();
int __cdecl sub_401160(FILE *Stream, char *Format, _locale_t Locale, va_list Arglist); // idb
int scanf_like(char *Format, ...);
int sub_401284();
int sub_40128C();
int __cdecl UserMathErrorFunction();
int sub_401838();
void sub_401842();
char sub_40184E();
// int __scrt_initialize_default_local_stdio_options(void); weak
BOOL sub_401892();
void *sub_40189E();
void *sub_4018A4();
LPTOP_LEVEL_EXCEPTION_FILTER sub_401A0C();
// LONG __stdcall __scrt_unhandled_exception_filter(struct _EXCEPTION_POINTERS *ExceptionInfo); idb
void sub_401A6E();
void sub_401A76();
void __cdecl sub_401AA2(); // idb
// int __cdecl set_new_mode(int NewMode);

//-------------------------------------------------------------------------
// Data declarations

// extern LPTOP_LEVEL_EXCEPTION_FILTER (__stdcall *SetUnhandledExceptionFilter)(LPTOP_LEVEL_EXCEPTION_FILTER lpTopLevelExceptionFilter);
// extern void (__stdcall *InitializeSListHead)(PSLIST_HEADER ListHead);
// extern int (__cdecl *_stdio_common_vfprintf)(unsigned __int64 Options, FILE *Stream, const char *Format, _locale_t Locale, va_list ArgList);
// extern int (__cdecl *_stdio_common_vfscanf)(unsigned __int64 Options, FILE *Stream, const char *Format, _locale_t Locale, va_list Arglist);
// extern FILE *(__cdecl *_acrt_iob_func)(unsigned int Ix);
int dword_40300C = 1; // weak
union _SLIST_HEADER ListHead; // idb
int dword_403360; // weak
_UNKNOWN unk_403370; // weak
_UNKNOWN unk_403378; // weak
_UNKNOWN unk_403380; // weak
_UNKNOWN unk_403384; // weak


//----- (00401000) --------------------------------------------------------
int __cdecl main(int argc, const char **argv, const char **envp)
{
  int v4;      // [esp+0h] [ebp-Ch]
  int v5;     // [esp+4h] [ebp-8h] BYREF

  scanf_like("%d", v5);
  v4 = user_defined(*(int *)v5);
  printf_like("Num %d took total %d iterations\n", v5, v4);
  return 0;
}

//----- (00401060) --------------------------------------------------------
int __cdecl user_defined(int a1)
{
  int v2; // [esp+0h] [ebp-4h]

  v2 = 0;
  while ( a1 != 1 )
  {
    if ( a1 % 2 )
      a1 = 3 * a1 + 1;
    else
      a1 /= 2;
    printf_like("%d iteration: %d\n", ++v2, a1);
  }
  return v2;
}

//----- (004010D0) --------------------------------------------------------
void *sub_4010D0()
{
  return &unk_403378;
}

//----- (004010E0) --------------------------------------------------------
int __cdecl sub_4010E0(FILE *Stream, char *Format, _locale_t Locale, va_list ArgList)
{
  unsigned __int64 *v4; // eax

  v4 = (unsigned __int64 *)sub_4010D0();
  return _stdio_common_vfprintf(*v4, Stream, Format, Locale, ArgList);
}

//----- (00401110) --------------------------------------------------------
int printf_like(char *Format, ...)
{
  FILE *v1; // eax
  va_list va; // [esp+14h] [ebp+Ch] BYREF

  va_start(va, Format);
  v1 = _acrt_iob_func(1u);
  return sub_4010E0(v1, Format, 0, va);
}

//----- (00401150) --------------------------------------------------------
void *sub_401150()
{
  return &unk_403370;
}

//----- (00401160) --------------------------------------------------------
int __cdecl sub_401160(FILE *Stream, char *Format, _locale_t Locale, va_list Arglist)
{
  _DWORD *v4; // eax
  unsigned __int64 v6; // [esp-18h] [ebp-18h]

  v4 = sub_401150();
  HIDWORD(v6) = v4[1];
  LODWORD(v6) = *v4 | 1;
  return _stdio_common_vfscanf(v6, Stream, Format, Locale, Arglist);
}

//----- (00401190) --------------------------------------------------------
int scanf_like(char *Format, ...)
{
  FILE *v1; // eax
  va_list va; // [esp+14h] [ebp+Ch] BYREF

  va_start(va, Format);
  v1 = _acrt_iob_func(0);
  return sub_401160(v1, Format, 0, va);
}

//----- (00401284) --------------------------------------------------------
int sub_401284()
{
  __scrt_initialize_default_local_stdio_options();
  return 0;
}
// 401875: using guessed type int __scrt_initialize_default_local_stdio_options(void);

//----- (0040128C) --------------------------------------------------------
int sub_40128C()
{
  int v0; // eax

  sub_401A0C();
  v0 = UserMathErrorFunction();
  return set_new_mode(v0);
}

//----- (00401835) --------------------------------------------------------
int __cdecl UserMathErrorFunction()
{
  return 0;
}

//----- (00401838) --------------------------------------------------------
int sub_401838()
{
  return 1;
}

//----- (00401842) --------------------------------------------------------
void sub_401842()
{
  InitializeSListHead(&ListHead);
}

//----- (0040184E) --------------------------------------------------------
char sub_40184E()
{
  return 1;
}

//----- (00401892) --------------------------------------------------------
BOOL sub_401892()
{
  return dword_40300C == 0;
}
// 40300C: using guessed type int dword_40300C;

//----- (0040189E) --------------------------------------------------------
void *sub_40189E()
{
  return &unk_403384;
}

//----- (004018A4) --------------------------------------------------------
void *sub_4018A4()
{
  return &unk_403380;
}

//----- (00401A0C) --------------------------------------------------------
LPTOP_LEVEL_EXCEPTION_FILTER sub_401A0C()
{
  return SetUnhandledExceptionFilter(__scrt_unhandled_exception_filter);
}

//----- (00401A6E) --------------------------------------------------------
void sub_401A6E()
{
  dword_403360 = 0;
}
// 403360: using guessed type int dword_403360;

//----- (00401A76) --------------------------------------------------------
void sub_401A76()
{
  ;
}
// 401A76: could not find valid save-restore pair for edi

//----- (00401AA2) --------------------------------------------------------
void __cdecl sub_401AA2()
{
  ;
}
// 401AA2: could not find valid save-restore pair for edi

// nfuncs=79 queued=21 decompiled=21 lumina nreq=0 worse=0 better=0
// ALL OK, 21 function(s) have been successfully decompiled
